site_name: Passwordless Auth For FastAPI
theme:
  name: material

repo_name: fastapi-passwordless
repo_url: https://github.com/amirasaad/fastapi-passwordless

nav:
  - FastApi Passwordless: index.md
  - 🔨 Installation: install.md
  - 🕹 Getting Started: getting-started.md
  - Example: example.md
  - Contirbution: contribute.md
